### ISSUE TITLE
Plans to upgrade to Camera2

### ISSUE THREAD

**Issue by garrettlangley** [kevalpatel2106/android-hidden-camera#11]
@kevalpatel2106 any plans to migrate this to Camera2 now that Camera is deprecated?

**Comment by kevalpatel2106** [comment]
@garrettlangley As of now, I don't have time to migrate the library to Camera2 API. But if you can, I will be happy to merge PR. 

I did not work on Camera2 API. Will it be supported by API < 20? Is it backward compatible?
