### ISSUE TITLE
setParameters failed

### ISSUE THREAD

**Issue by hussainbadri21** [kevalpatel2106/android-hidden-camera#2]
Unable to set parameters in certain devices(Redmi Note 3)
```
List<Camera.Size> pictureSizes = mCamera.getParameters().getSupportedPictureSizes();

        //set the preview sizes that are the lowest, as we don't have to display the preview.
        parameters.setPreviewSize(pictureSizes.get(pictureSizes.size() - 1).width,
                pictureSizes.get(pictureSizes.size() - 1).height);

        //set the camera image size based on config provided
        Camera.Size cameraSize;
        switch (mCameraConfig.getResolution()) {
            case CameraResolution.HIGH_RESOLUTION:
                cameraSize = pictureSizes.get(0);   //Highest res
                break;
            case CameraResolution.MEDIUM_RESOLUTION:
                cameraSize = pictureSizes.get(pictureSizes.size() / 2);     //Resolution at the middle
                break;
            case CameraResolution.LOW_RESOLUTION:
                cameraSize = pictureSizes.get(pictureSizes.size() - 1);       //Lowest res
                break;
            default:
                throw new RuntimeException("Invalid camera resolution.");
        }
        parameters.setPictureSize(cameraSize.width, cameraSize.height);
```
removing this code under CamPreview.java fixes the issue.
Can you please remove it and push

**Comment by kevalpatel2106** [comment]
@hussainbadri21 Can you send me error log? Why this is not working? Any idea?

**Comment by hussainbadri21** [comment]
> FATAL EXCEPTION: main
>                                                                            Process: com.kevalpatel2106.sample, PID: 24974
>                                                                            java.lang.RuntimeException: setParameters failed
>                                                                                at android.hardware.Camera.native_setParameters(Native Method)
>                                                                                at android.hardware.Camera.setParameters(Camera.java:1979)
>                                                                                at com.androidhiddencamera.CameraPreview.surfaceChanged(CameraPreview.java:114)
>                                                                                at android.view.SurfaceView.updateWindow(SurfaceView.java:669)
>                                                                                at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:185)
>                                                                                at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
>                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2007)
>                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1098)
>                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5933)
>                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
>                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:588)
>                                                                                at android.view.Choreographer.doFrame(Choreographer.java:558)
>                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
>                                                                                at android.os.Handler.handleCallback(Handler.java:739)
>                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                at android.os.Looper.loop(Looper.java:135)
>                                                                                at android.app.ActivityThread.main(ActivityThread.java:5276)
>                                                                                at java.lang.reflect.Method.invoke(Native Method)
>                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
>                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
http://stackoverflow.com/questions/3890381/camera-setparameters-failed-in-android

**Comment by kevalpatel2106** [comment]
@hussainbadri21 I checked the sample app on Redmi 3s and it's working correctly. Can you send me the code where you set the camera configurations?

**Comment by kevalpatel2106** [comment]
@hussainbadri21 I fixed this issue in commit [8275f09f3784fbd13c5d8d4a9cee89782ea00c71 ](https://github.com/kevalpatel2106/android-hidden-camera/commit/8275f09f3784fbd13c5d8d4a9cee89782ea00c71). Can you confirm that now it is working? I also updated sample apk.

**Comment by hussainbadri21** [comment]
Issue is now fixed and the app works as expected. Could you please update the library version with the new changes

**Comment by kevalpatel2106** [comment]
@hussainbadri21 Sure I will update it soon.

**Comment by kevalpatel2106** [comment]
@hussainbadri21 v1.2 is live with above fix. Check that out.

**Comment by hussainbadri21** [comment]
Thanks a lot,everything is working fine now. 

    On Friday, December 16, 2016 1:04 PM, Keval Patel <notifications@github.com> wrote:
 

 @hussainbadri21 v1.2 is live with above fix. Check that out.—

**Comment by utkarshnextgn** [comment]
I Want to take Picture on fixed Interval of time After Every 2 Sec Can You Provide Me the Source code  or any idea about this one.Actually I am trying A lot Of Concept bt not Working.Can You Provide Me Any Idea

**Comment by utkarshnextgn** [comment]
It Means When I click On Take Photo It Will Start To Take image On Fixed Interval Otherwise iT will take 4 or 5 photos Automatically. proviede me Some Idea I Am really Gratefull to you.
and i need this one Very much

**Comment by utkarshnextgn** [comment]
And for providing this library thankyou
