### ISSUE TITLE
Able to rename the file name of the generated image file from the Hidden Camera

### ISSUE THREAD

**Issue by jaira** [kevalpatel2106/android-hidden-camera#35]
Hi Keval :)

Thank you so much for creating this awesome hidden camera library.

I was wondering if we have the mechanism to rename the imageFile generated from the Hidden Camera? :)

Thank you so much for your reply. :)

**Comment by kevalpatel2106** [comment]
@jaira You can provide a file to store the captured image using `CameraConfig.Builder#setImageFile()`.  Check out in the source code: https://github.com/kevalpatel2106/android-hidden-camera/blob/master/hiddencamera/src/main/java/com/androidhiddencamera/CameraConfig.java#L75
