### ISSUE TITLE
Can't install app on devices that do not support camera autofocus. 

### ISSUE THREAD

**Issue by pavlomelnyk** [kevalpatel2106/android-hidden-camera#39]
Hi.
So not all devices support camera autofocus but the still have camera and can use them. 
You have to add 
`<uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />`
in your manifest so that thous devices can install the app that uses your library.
Repo example that had the same problem. Scroll bottom to see fix.
https://github.com/jitsi/jitsi-meet/issues/1736

Best

**Comment by kevalpatel2106** [comment]
@pavlomelnyk Thank you for the issue. Can you generate the PR for the fix of this issue?

**Comment by kevalpatel2106** [comment]
I fixed this issue in 78c7026e99e1650be387818e916a4243458a667c.
