### ISSUE TITLE
Take picture in second time error

### ISSUE THREAD

**Issue by wisnukurniawan** [kevalpatel2106/android-hidden-camera#4]
When i click takepicture in second time. i get error
i think it has been handling in takePicture() method.

**Comment by kevalpatel2106** [comment]
@wisnukurniawan Can you tell me which error you are getting? Post your staketrace if possible.

**Comment by wisnukurniawan** [comment]
![takepicture-method](https://cloud.githubusercontent.com/assets/16729158/21713597/451ea008-d42d-11e6-9ca4-7d80252682bc.JPG)

**Comment by wisnukurniawan** [comment]
to handle that i put this 
`                if (myImage== null)  takePicture();
`

**Comment by kevalpatel2106** [comment]
@wisnukurniawan I will look into this and get back to you.

**Comment by kevalpatel2106** [comment]
@wisnukurniawan Updated the source code with the fix. Can you recheck the issue with updated source code?

**Comment by wisnukurniawan** [comment]
how to update the library?

**Comment by kevalpatel2106** [comment]
@wisnukurniawan You can add the library as a module in you project instead of the gradle dependency.

**Comment by kevalpatel2106** [comment]
@wisnukurniawan I will publish the updated version soon.

**Comment by wisnukurniawan** [comment]
Thankyou @kevalpatel2106  youre da MVP (y)

**Comment by kevalpatel2106** [comment]
Fixed in [v1.2.1](https://github.com/kevalpatel2106/android-hidden-camera/releases/tag/v1.2.1)
