### ISSUE TITLE
 Attempt to invoke virtual method 'void android.hardware.Camera.setDisplayOrientation(int)' on a null object reference

### ISSUE THREAD

**Issue by kevalpatel2106** [kevalpatel2106/android-hidden-camera#7]
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setDisplayOrientation(int)' on a null object reference
com.a.c.surfaceCreated ()
android.view.SurfaceView.updateWindow (SurfaceView.java:709)
android.view.SurfaceView$3.onPreDraw (SurfaceView.java:208)
android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:1018)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2308)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1301)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7016)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:777)
android.view.Choreographer.doCallbacks (Choreographer.java:590)
android.view.Choreographer.doFrame (Choreographer.java:560)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:763)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6946)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)

**Comment by mubasoft** [comment]
@kevalpatel2106  Did u find any solution for this bug?

**Comment by kevalpatel2106** [comment]
Fix in next release.

**Comment by Corical** [comment]
So when is this 'next release' ?

**Comment by luolugithub** [comment]
I encountered the same question，how to solve this problem?

**Comment by FoxsTail** [comment]
Your camera object is instantiated only if there is no Exception. So, if this exception happens, camera == null.
