### ISSUE TITLE
app passed NULL surface

### ISSUE THREAD

**Issue by karthikn-jay** [kevalpatel2106/android-hidden-camera#9]
There is some delay when the HiddenCameraService is started (please refer 1st and 2nd lines from below log).

Then after a while (about 5-10 seconds), the image is captured (pls refer 3rd line in the below log)

D/Camera: app passed NULL surface
I/Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
D/Image capture: 1376498

Device: Moto G4+

**Comment by kevalpatel2106** [comment]
> Then after a while (about 5-10 seconds), the image is captured (pls refer 3rd line in the below log)

This is because, in the source code of the sample apk, it is programmed to capture the image after 10 seconds. This is not a bug.😊
